name: Auto Release Localhost Servers

on:
  push:
    branches:
      - main
    paths:
      - 'localhost_servers/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/gh-action@v2

      - name: Delete previous release (if exists)
        run: |
          gh release delete servers-latest -y || echo "No existing release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Zip localhost_servers
        run: |
          mkdir release
          git ls-files localhost_servers | zip -@ release/servers.zip

      - name: Create servers-latest release
        run: |
          gh release create servers-latest release/servers.zip \
            --title "Localhost Servers Latest" \
            --notes "This is the latest version of localhost servers for Neurite."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
