name: Auto Release Localhost Servers

on:
  push:
    branches:
      - main
    paths:
      - 'localhost_servers/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ensure GitHub CLI is installed
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GH CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Delete existing release if it exists
        run: |
          gh release delete servers-latest -y || echo "No release to delete"

      - name: Create servers.zip (tracked files only)
        run: |
          mkdir release
          git ls-files localhost_servers | zip -@ release/servers.zip

      - name: Create new release
        run: |
          gh release create servers-latest release/servers.zip \
            --title "Localhost Servers Latest" \
            --notes "Latest release of localhost servers for Neurite"
